### PR TITLE
randomize order of root_urls

### PR DESCRIPTION
**Pull request by ail1020**

### CODE REVIEW

**Comment by 1tayH** [comment]
Hi, thanks for the PR!
Is it just me or is the spacing a bit off?

**Comment by 2three8** [comment]
Um thanks but I doubt it will rocket you to fame.  I'm not much of an
expert on Linux. More of a casual amateur. Grappling with just sed at the
moment and haven't found a comfortable editor yet. And I need to refresh my
skills on crontab for this.
I'll have a look tomorrow.
Andy

**Comment by ail1020** [comment]
@1tayH I reduced the indents because it is no longer inside a for loop if that's what you're referring too.

@2three8 Am I missing something?

**Comment by 2three8** [comment]
Hi, this doesn't look to me to have an exit from the url list.
The for loop which obviously finished at the end of the list has been taken out and replaced with a random selection from the url.
The while loop goes on forever ?
Have I missed a time out ?
A

**Comment by 2three8** [comment]
Ok. To me (new to Python) looks like the time out is only on depth of links within an URL (so a smallish number is sensible). Whereas I assumed the timeout was to exit the program (so a largish number and more likely to want to be tens of minutes). Is the description of the timeout argument a bit misleading?It makes more sense to me now that program continues until killed by an outside command - say a cron job to launch it and then to kill it ?

**Comment by 1tayH** [comment]
I agree, the logging statement should be taken out as it will never get hit.
As for the timeout, @2three8, it was originally added so the CI wouldn't keep on running the script forever when testing it, this PR doesn't break it 😄

**Comment by 2three8** [comment]
@1tayH I ran with the timeout arg. I understand it now. Amazing what actually trying something does !  It's been a while since I worked through code logic.

**Comment by ail1020** [comment]
I removed that unused debug line.

**Pull request merged**
